name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Test with environment variables
      run: echo $TAG_NAME
      env:
        TAG_NAME: muhammadbilalyar:platformservice:${{ steps.date.outputs.date }}-${{ env.GITHUB_ACTION }}
    - name: Build the Docker image
      run: docker build -f "PlatformService/Dockerfile-github" . ${{ env.TAG_NAME }}
